AWSTemplateFormatVersion: "2010-09-09"
Description: App Runner service pulling from ECR :latest

Parameters:
  ServiceName:
    Type: String
    Default: movenet-backend-svc
  ECRRepoUri:
    Type: String
    Description: Full ECR repo URI (e.g., 123456789012.dkr.ecr.ap-south-1.amazonaws.com/movenet-backend)
  ImageTag:
    Type: String
    Default: latest
  Cpu:
    Type: String
    Default: "1 vCPU"
    AllowedValues: ["1 vCPU","2 vCPU"]
  Memory:
    Type: String
    Default: "2 GB"
    AllowedValues: ["2 GB","3 GB","4 GB"]

Resources:
  AppRunnerECRAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ServiceName}-ECRAccessRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: apprunner.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  Service:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Ref ServiceName
      SourceConfiguration:
        AutoDeploymentsEnabled: true
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerECRAccessRole.Arn
        ImageRepository:
          ImageIdentifier: !Sub "${ECRRepoUri}:${ImageTag}"
          ImageRepositoryType: ECR
          ImageConfiguration:
            Port: "8000"
            RuntimeEnvironmentVariables:
              - Name: ALLOW_CLOUDWATCH
                Value: "true"
              - Name: ENV
                Value: "prod"
      InstanceConfiguration:
        Cpu: !Ref Cpu
        Memory: !Ref Memory
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/healthz"
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 3

Outputs:
  ServiceUrl:
    Value: !GetAtt Service.ServiceUrl
  ServiceStatus:
    Value: !GetAtt Service.Status