AWSTemplateFormatVersion: '2010-09-09'
Description: MoveNet - ECR repo per stage

Parameters:
  Project: { Type: String }
  Stage:   { Type: String }

Resources:
  Repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${Project}-${Stage}'
      ImageScanningConfiguration: { ScanOnPush: true }
      ImageTagMutability: MUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              { "rulePriority": 1, "description": "keep last 20",
                "selection": { "tagStatus": "any", "countType": "imageCountMoreThan", "countNumber": 20 },
                "action": { "type": "expire" } }
            ]
          }

Outputs:
  RepositoryUri: { Value: !GetAtt Repo.RepositoryUri }
  RepositoryName: { Value: !Ref Repo }
