name: Frontend CI/CD (S3 + optional CloudFront)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync frontend s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        if: ${{ secrets.CF_DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation             --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }}             --paths "/*"